# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clay Heaton
email: ccheaton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tinker, tailor, hacker, dad
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clayheaton.github.io" # the base hostname & protocol for your site
twitter_username: clayheaton
github_username:  clayheaton

# Build settings
markdown: kramdown
